# Generated by Django 3.2.12 on 2024-02-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('nickname', models.CharField(max_length=250)),
                ('birthdate', models.CharField(max_length=10)),
                ('gardion', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('nationality', models.CharField(max_length=250)),
                ('cls', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=550)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('teacher', models.CharField(max_length=250)),
                ('enrollmentdate', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('sub', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('zip', models.CharField(max_length=6)),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
